defmodule Euler29 do
  @moduledoc """
  How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100
  and 2 ≤ b ≤ 100?
  """

  def solve do
    for a <- 2..100, b <- 2..100,
      into: MapSet.new do
      Math.pow(a, b)
    end
    |> MapSet.size
  end

end
